### ISSUE TITLE
Linear RGB/sRGB conversion question

### ISSUE THREAD

**Issue by JeffreyPalmer** [Shinmera/colored#2]
Hi!

Thanks for creating this library! I've been migrating my creative coding workflow to Common Lisp and was pleased to find it.

One question regarding the conversion between linear RGB and sRGB: It looks like you're applying a fixed gamma conversion instead of using something like the equation here: https://www.nayuki.io/page/srgb-transform-library, but I'm not really an expert on how this library works yet so I might be missing something. If not, was this an intentional choice, or is this something that you would consider adding to the library? I could try my hand at creating a PR, if so.

Thanks again!

**Comment by JeffreyPalmer** [comment]
Do you care if I remove the existing sRGB/RGB conversion functions, or would you prefer that they be kept around as an option? If so, I'm not sure how to override the `convert` method for both types of conversion (I'm a CL noob, lol).

**Comment by Shinmera** [comment]
No, just replace them.

**Comment by JeffreyPalmer** [comment]
I believe that this should work, but I did something to my environment yesterday and now I'm unable to run the package tests. When I try to run the tests for the package I get the following:

```
* (asdf:test-system :colored)
; compiling file "/Users/jeff/.quicklisp/local-projects/colored/test.lisp" (written 21 MAY 2024 03:04:22 PM):

; wrote /Users/jeff/.cache/common-lisp/sbcl-2.4.4-macosx-x64/Users/jeff/.quicklisp/local-projects/colored/test-tmpAR3FSGEY.fasl
; compilation finished in 0:00:00.035

debugger invoked on a UNDEFINED-FUNCTION @54600B04 in thread
#<THREAD tid=259 "main thread" RUNNING {1003F080A3}>:
  The function ORG.SHIRAKUMO.ALLOY.COLORED::%RGB is undefined.
```

If you happen to have any ideas as to what might be causing this please let me know; it's driving me crazy.

Regardless, thanks for the package!

**Comment by Shinmera** [comment]
Tests run through fine on my system.
